name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to upload release assets
    strategy:
      matrix:
        go-version: [1.21]
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        exclude:
          # Exclude unsupported combinations
          - os: darwin
            arch: arm64
          - os: windows
            arch: arm64
          # Add new exclusion for linux/arm64
          - os: linux
            arch: arm64
    env:
      CGO_ENABLED: 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: src/go.sum

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        cd src
        output="../mcp-starter-${{ matrix.os }}-${{ matrix.arch }}"
        if [ "${{ matrix.os }}" = "windows" ]; then 
          output="$output.exe"
          mv main_windows.go main.go
        fi
        go build -o $output

    - name: Package Windows Executable
      if: matrix.os == 'windows'
      run: |
        zip mcp-starter-windows-${{ matrix.arch }}.zip mcp-starter-windows-${{ matrix.arch }}.exe

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./mcp-starter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
        asset_name: mcp-starter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
        asset_content_type: application/octet-stream

    - name: Generate Checksums
      run: |
        sha256sum mcp-starter-* > checksums.txt

    - name: Upload Checksums
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain 